---
kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: workload-web-app
  namespace: test-app
spec:
  replicas: 1
  selector:
    app: workload-web-app
    deploymentconfig: workload-web-app
    metadata:
      labels:
        app: workload-web-app
        deploymentconfig: workload-web-app
      annotations:
    spec:
      containers:
        - name: workload-web-app
          image: >-
            quay.io/integreatly/workload-web-app:master
          ports:
            - containerPort: 8080
              protocol: TCP
          imagePullPolicy: IfNotPresent
      restartPolicy: Always

