kind: Template
apiVersion: v1
metadata:
  name: workload-web-app
objects:
  - kind: DeploymentConfig
    apiVersion: apps.openshift.io/v1
    metadata:
      name: workload-web-app
    spec:
      replicas: 1
      selector:
        app: workload-web-app
        deploymentconfig: workload-web-app
      template:
        metadata:
          labels:
            app: workload-web-app
            deploymentconfig: workload-web-app
          annotations:
        spec:
          containers:
            - name: workload-web-app
              image: >-
                quay.io/integreatly/workload-web-app:master
              ports:
                - containerPort: ${{PORT}}
                  protocol: TCP
              imagePullPolicy: Always
              env:
                - name: PORT
                  value: ${PORT}
                - name: AMQ_ADDRESS
                  value: ${AMQ_ADDRESS}
                - name: AMQ_QUEUE
                  value: ${AMQ_QUEUE_NAME}
                - name: ENVIRONMENT
                  value: production
          restartPolicy: Always
  - kind: Service
    apiVersion: v1
    metadata:
      name: workload-web-app
      labels:
        app: workload-web-app
        deploymentconfig: workload-web-app
    spec:
      ports:
        - name: http
          protocol: TCP
          port: ${{PORT}}
          targetPort: ${{PORT}}
      selector:
        deploymentconfig: workload-web-app
      sessionAffinity: None
parameters:
  - name: PORT
    description: Port number
    value: "8080"
  - name: AMQ_ADDRESS
    description: The URL to connect to an AMQ address
  - name: AMQ_QUEUE_NAME
    description: The queue name to use for the AMQ address